#
# N3 project Scrutinizer configuration file
#
# @see https://scrutinizer-ci.com/docs/configuration
#

build:
  environment:
    php:
      version: '7.1'
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: 'make coverage'
            coverage:
              file: './dist/tests.clover'
              format: clover
