#
# N3 project Travis configuration
#
# @see https://docs.travis-ci.com/user/customizing-the-build/
#

language: php

php:
  - 7.1
  - 7.2

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - make install

script:
  - make test
