root.get.v1:
    path: /
    controller: resource.root:get
    methods: [GET]
    options:
        stability: stable
        deprecated: []
        version: 1

domains.domain.delete.v1:    
    path: /domains/{domain}
    controller: resource.domains.domain:delete
    methods: [DELETE]
    options:
        stability: stable
        deprecated: []
        version: 1

domains.domain.enable.post.v1:
    path: /domains/{domain}/actions/enable
    controller: resource.domains.domain.enable:post
    options:
          stability: stable
          deprecated: []
          version: 1
